[package]
name = "pixhawk-proxy"
version = "0.1.0"
authors = ["Michal Podhradsky <mpodhradsky@galois.com>"]
build = "build.rs"

[build-dependencies]
protobuf-codegen-pure = "2.0"

[dependencies]
lmcp = { path = "../rust-lmcp" }
mavlink = { path = "../rust-mavlink" }
protobuf = "2.0"